"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, LoaderCircle, MessageSquareText, Send, Trash2 } from "lucide-react";
import { Badge, Button, GhostButton, Spinner, Textarea } from "@/components/ui";
import { CATEGORY_LABEL } from "@/lib/constants";
import { formatDate, initials } from "@/lib/format";

type Comment={id:string;content:string;isAccepted:boolean;createdAt:string;author:{id:string;name:string;role:string}};
type Thread={id:string;title:string;content:string;category:keyof typeof CATEGORY_LABEL;tags:string[];authorId:string;author:{name:string};createdAt:string;comments:Comment[]};
export default function ForumDetailPage(){
 const {id}=useParams<{id:string}>();const router=useRouter();const [data,setData]=useState<{thread:Thread;canManage:boolean;currentUserId:string}|null>(null);const [sending,setSending]=useState(false);const load=()=>fetch(`/api/forum/${id}`).then(r=>r.json()).then(setData);useEffect(()=>{load()},[id]);
 async function reply(e:FormEvent<HTMLFormElement>){e.preventDefault();setSending(true);const f=new FormData(e.currentTarget);const r=await fetch(`/api/forum/${id}/comments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:f.get("content")})});setSending(false);if(r.ok){e.currentTarget.reset();load()}}
 async function accept(commentId:string){const r=await fetch(`/api/forum/${id}/comments/${commentId}/accept`,{method:"PUT"});if(r.ok)load()}
 async function remove(){if(!confirm("Delete this discussion and all replies?"))return;const r=await fetch(`/api/forum/${id}`,{method:"DELETE"});if(r.ok)router.push("/forum")}
 if(!data?.thread)return <Spinner/>;const t=data.thread;
 return <div className="mx-auto max-w-5xl"><Link href="/forum" className="mb-7 inline-flex items-center gap-2 text-sm text-[var(--text-soft)]"><ArrowLeft className="h-4 w-4"/> Forum</Link><section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><Badge>{CATEGORY_LABEL[t.category]}</Badge>{t.comments.some(c=>c.isAccepted)?<Badge tone="success"><CheckCircle2 className="mr-1 h-3 w-3"/> Solved</Badge>:null}</div><h1 className="mt-4 text-3xl font-semibold tracking-[-0.04em]">{t.title}</h1><p className="mt-5 whitespace-pre-wrap text-sm leading-7 text-[var(--text-soft)]">{t.content}</p><div className="mt-5 text-xs text-[var(--text-muted)]">Asked by {t.author.name} · {formatDate(t.createdAt)}</div></div>{data.canManage?<GhostButton onClick={remove} className="text-[var(--danger)]"><Trash2 className="h-4 w-4"/></GhostButton>:null}</div>{t.tags.length?<div className="mt-5 flex flex-wrap gap-2">{t.tags.map(tag=><span key={tag} className="rounded-lg bg-[var(--surface-soft)] px-2.5 py-1 text-xs text-[var(--text-muted)]">#{tag}</span>)}</div>:null}</section><div className="mt-7 flex items-center gap-2"><MessageSquareText className="h-4 w-4 text-[var(--primary)]"/><h2 className="text-sm font-semibold">{t.comments.length} replies</h2></div><div className="mt-3 space-y-3">{t.comments.map(c=><article key={c.id} className={`rounded-2xl border bg-[var(--surface)] p-5 ${c.isAccepted?"border-emerald-300/60 ring-4 ring-emerald-100/40 dark:border-emerald-800 dark:ring-emerald-950/20":"border-[var(--border)]"}`}><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[var(--surface-soft)] text-xs font-semibold">{initials(c.author.name)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium">{c.author.name}</span><span className="text-xs text-[var(--text-muted)]">{formatDate(c.createdAt)}</span>{c.isAccepted?<Badge tone="success">Accepted solution</Badge>:null}</div><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-[var(--text-soft)]">{c.content}</p>{data.canManage&&!c.isAccepted?<button onClick={()=>accept(c.id)} className="mt-4 inline-flex items-center gap-1.5 text-xs font-medium text-[var(--success)]"><CheckCircle2 className="h-3.5 w-3.5"/> Mark as solution</button>:null}</div></div></article>)}</div><form onSubmit={reply} className="mt-5 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="mb-3 text-sm font-semibold">Add your reply</div><Textarea name="content" className="min-h-[150px]" placeholder="Share the reasoning, fix, or trade-off..." required/><div className="mt-3 flex justify-end"><Button disabled={sending}>{sending?<LoaderCircle className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>} Reply</Button></div></form></div>;
}
